language: python
python:
  - '3.6'
install:
  - pip install -r requirements-dev.txt
script:
  - pytest
  - make sphinx
  - flake8 bootstrap_example_package
before_deploy:
  - make sphinx
  - pip install --upgrade setuptools wheel
  - python setup.py sdist bdist_wheel  
deploy:
  - provider: pages
    skip_cleanup: true
    local-dir: docs/build/html
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      tags: true
  - provider: pypi
    server: https://testpypi.python.org/pypi # Remove for deployment to official PyPi repo
    skip_cleanup: true
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    on:
      tags: true